version: '3'

services:
    database:
        restart: always
        image: postgres:12.2
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: [5432]
        volumes:
            - postgres-data:/var/lib/postgresql/data

    mailcatcher:
        image: schickling/mailcatcher
        ports: [1025, 1080]

volumes:
    postgres-data:
